### PR TITLE
When user tries to create an object without ID return 400 not 403

### LINKED ISSUE #101: Wonky exception type
When Elide [fails to assign an ID](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/parsers/state/CollectionTerminalState.java#L185) it responds with `403 Forbidden`, this feels misleading. I think elide should respond with `400 Bad Request` instead.

### PR DESCRIPTION
**Pull request by clayreimann**
Closes #101

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

File: elide-core/src/main/java/com/yahoo/elide/core/exceptions/HttpStatusException.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
  * Creates fast exceptions without stack traces since filter checks can throw many of these.
  */
 @Slf4j
-public class HttpStatusException extends RuntimeException {
+abstract public class HttpStatusException extends RuntimeException {
```
Comment (DeathByTape) [inline elide-core/src/main/java/com/yahoo/elide/core/exceptions/HttpStatusException.java]: *sigh* this is _very_ pedantic (sorry about that) but it's more common to see `public abstract class` than `abstract public class` (i.e. flip `abstract` and `public`).

Would you mind updating this so we can remain consistent?

**Comment by DeathByTape** [comment]
Just my one nit-pick comment :)

Then 👍
