### PR TITLE
Fixes #1244: Incorrect pagination with ToMany filtering

### LINKED ISSUE #1244: Incorrect pagination with ToMany filtering
## Expected Behavior
When issuing query with filter on ToMany relationship and pagination should return correct number of results vs page size

## Current Behavior
When issuing query with filter on ToMany relationship and pagination,
then resulting product of join vs distinct rows differs resulting in broken pagination

## Possible Solution
distinct should be applied in this case

## Your Environment

* Elide version used: 4.5.14
* Environment name and version (Java 11.0.2):
* Operating System and version:
* Link to your project: https://github.com/FAForever/faf-java-api/issues/338

### PR DESCRIPTION
**Pull request by bukajsytlos**
Resolves #1244

## Description
When creating query, check if pagination and ToMany relationship is present, if so add DISTINCT to query.

## Motivation and Context
See the issue

## How Has This Been Tested?
Unit tests

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java [hunk 1]
```diff
@@ -128,6 +129,56 @@ public void testRootFetchWithJoinFilter() {
         assertEquals(expected, actual);
     }
 
+    @Test
+    public void testDistinctRootFetchWithToManyJoinFilterAndPagination() {
```
Comment (aklish) [inline elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java:133]: Can we test the exception behavior as well?

Comment (bukajsytlos) [reply elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java:133]: yes, there is/are failing tests right now because of this, but I am struggling little bit with running and debugging them locally. when I resolve that, I'll try to write test for this case

File: elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java [hunk 2]
```diff
@@ -128,6 +129,56 @@ public void testRootFetchWithJoinFilter() {
...
+        final Pagination pagination = Pagination.fromOffsetAndLimit(10, 0, false);
+        List<Path.PathElement> chapterTitlePath = Arrays.asList(
```
[the remark this answers is not in the document]
Comment (bukajsytlos) [reply elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/RootCollectionFetchQueryBuilderTest.java:135]: ok, I just copied this from other test :)

**Comment by bukajsytlos** [comment]
@aklish I am slightly confused. There was a failing test in SortingIT which I have changed here. Looks like elide is creating default pagination, but I don't understand under which conditions. I guess users won't be happy if my change would throw exceptions on them, when they are not specifying pagination, but my exception states otherwise

**Comment by aklish** [comment]
Elide puts a cap on the number of records returned if the client doesn't provide pagination params.  That's called _default pagination_.  There is a global setting that sets how many records this is - typically something large like 10k.

**Comment by aklish** [comment]
Overall - the change is correct.  I'm not sure if this will break anyone's use case - but I'm hoping it won't.  We'll do a a minor version release.
