### PR TITLE
Issue754

### LINKED ISSUE #754: mutation throwing shared permission exception
I have two tables with 1 to many relationship: Parent and child 
I have one existing parent record with id: 1

when I am trying to insert a new child using below query-

```
mutation {
  parent(filter: "id==1") {
    edges {
      node {
        id
        childs(op: UPSERT, data: {id: "b5aab819-4a31-41e0-a878-62a980e5e702", name: "test", status: "New"}) {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```

It is throwing below exception:

```
{
  "data": null,
  "errors": [
    {
      "message": "Exception while fetching data (/parent/edges[0]/node/childs) : null",
      "path": [
        "parent",
        "edges",
        0,
        "node",
        "childs"
      ],
      "exception": {
        "cause": null,
        "stackTrace": [],
        "status": 403,
        "expression": {
          "present": true
        },
        "evaluationMode": {
          "present": true
        },
        "loggedMessage": "ForbiddenAccessException: Message=SharePermission: \u001b[31mFAILURE\u001b[m\tMode=Optional[USER_CHECKS_ONLY]\tExpression=[Optional[\u001b[31mFAILURE\u001b[m]]",
        "verboseMessage": "SharePermission: \u001b[31mFAILURE\u001b[m",
        "verboseErrorResponse": {
          "403": {
            "errors": [
              "SharePermission: \u001b[31mFAILURE\u001b[m"
            ]
          }
        },
        "errorResponse": {
          "403": {
            "errors": [
              "ForbiddenAccessException"
            ]
          }
        },
        "localizedMessage": null,
        "message": null,
        "suppressed": []
      },
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "extensions": null,
      "errorType": "DataFetchingException"
    }
  ]
}
```
Parent is having update and shared permission and child is having insert and update permission. Package level permission is: insert-> none, update-> none, delete -> none

### PR DESCRIPTION
**Pull request by aklish**
Fix issue with non-primitive entity identifiers and GraphQL SharePermission.  Fixes #754.

### CODE REVIEW

File: elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java [hunk 1]
```diff
@@ -189,7 +189,7 @@ public boolean matchesId(String checkId) {
                 .map(checkId::equals)
                 .orElseGet(() -> {
                     String id = getId();
-                    return !"0".equals(id) && checkId.equals(id);
+                    return !"0".equals(id) && !"null".equals(id) && checkId.equals(id);
```
Comment (wcekan) [inline elide-core/src/main/java/com/yahoo/elide/core/PersistentResource.java]: Could be cleaner, but makes sense since it is currently using `String.valueOf`

**Comment by bappajubcse05** [comment]
Hello @aklish,

Could you please let me know the release timeline for this fix i,e, elide 5.0?

Thanks.
