### PR TITLE
Use Serializable Classes for RedisCache to work

### LINKED ISSUE #2680: Redis Cache unable to Store Query Result
Redis Cache unable to serialize results

## Expected Behavior
Caching should not fail.

-->

## Current Behavior
```
java.lang.IllegalArgumentException: Failed to serialize object of type: class com.yahoo.elide.datastores.aggregation.query.QueryResult
        at org.springframework.util.SerializationUtils.serialize(SerializationUtils.java:51)
        at com.yahoo.elide.datastores.aggregation.cache.RedisCache.put(RedisCache.java:41)
        at com.yahoo.elide.datastores.aggregation.AggregationDataStoreTransaction.loadObjects(AggregationDataStoreTransaction.java:128)
        at com.yahoo.elide.datastores.multiplex.MultiplexTransaction.loadObjects(MultiplexTransaction.java:65)
        at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.lambda$loadObjects$2(InMemoryStoreTransaction.java:117)
        at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.fetchData(InMemoryStoreTransaction.java:262)
        at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.loadObjects(InMemoryStoreTransaction.java:123)
        at com.yahoo.elide.core.PersistentResource.loadRecords(PersistentResource.java:373)
        at com.yahoo.elide.graphql.PersistentResourceFetcher.lambda$fetchObject$1(PersistentResourceFetcher.java:175)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at com.yahoo.elide.graphql.PersistentResourceFetcher.fetchObject(PersistentResourceFetcher.java:175)
        at com.yahoo.elide.graphql.containers.RootContainer.processFetch(RootContainer.java:21)
        at com.yahoo.elide.graphql.containers.RootContainer.processFetch(RootContainer.java:14)
        at com.yahoo.elide.graphql.PersistentResourceFetcher.fetchObjects(PersistentResourceFetcher.java:149)
        at com.yahoo.elide.graphql.PersistentResourceFetcher.get(PersistentResourceFetcher.java:91)
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:182)
        at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43)
        at graphql.execution.Async.eachSequentiallyImpl(Async.java:80)
        at graphql.execution.Async.eachSequentially(Async.java:69)
        at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38)
        at graphql.execution.Execution.executeOperation(Execution.java:160)
        at graphql.execution.Execution.execute(Execution.java:106)
        at graphql.GraphQL.execute(GraphQL.java:641)
        at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
        at graphql.GraphQL.executeAsync(GraphQL.java:524)
        at graphql.GraphQL.execute(GraphQL.java:450)
        at graphql.GraphQL.execute(GraphQL.java:420)
        at com.yahoo.elide.graphql.QueryRunner.executeGraphQLRequest(QueryRunner.java:303)
        at com.yahoo.elide.graphql.QueryRunner.run(QueryRunner.java:187)
        at com.yahoo.elide.async.operation.GraphQLAsyncQueryOperation.execute(GraphQLAsyncQueryOperation.java:41)
        at com.yahoo.elide.async.operation.AsyncQueryOperation.call(AsyncQueryOperation.java:43)
        at com.yahoo.elide.async.operation.AsyncQueryOperation.call(AsyncQueryOperation.java:27)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.NotSerializableException: com.yahoo.elide.datastores.aggregation.dynamic.DynamicModelInstance
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
        at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
        at java.base/java.util.ArrayList.writeObject(ArrayList.java:897)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
-->

## Possible Solution
Make `com.yahoo.elide.datastores.aggregation.dynamic.DynamicModelInstance` serializable

## Steps to Reproduce (for bugs)
1. Query an Agg Model using Redis for caching

### PR DESCRIPTION
**Pull request by moizarafat**
Resolves #2680 (if appropriate)

## Description
When using RedisCache we Serialize the QueryResult Object before store. To support serialization, we have to make multiple classes serializable.

## Motivation and Context
Error during Serialization.

## How Has This Been Tested?
Existing and New Test Cases.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by aklish** [comment]
@moizarafat How do these classes relate to QueryResult serialization?

**Comment by moizarafat** [comment]
> @moizarafat How do these classes relate to QueryResult serialization?

`QueryResult<T>` has a type defined so when the jobs were failing we had the type `TableType/DynamicModelInstance`. So had to make changes there and keep fixing any member classes and so on.

File: elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/TableSource.java [hunk 1]
```diff
@@ -35,7 +36,8 @@
 @AllArgsConstructor
 @NoArgsConstructor
 @Builder
-public class TableSource {
```
Comment (aklish) [inline elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/TableSource.java:38]: Why would these classes need serialization?  They are just HJSon Configuration?

**Comment by aklish** [comment]
Java serialization is about the slowest, least compact form of serialization out there.  Jackson/JSON would even be better.   It would be nice not to require serializable for Redis Caching to work - it seems like a future source of bugs.

File: elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/TableSource.java (hunk 1 above)
Comment (aklish) [reply elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/TableSource.java:38]: It would be nice if RedisCache didn't require changes to the underlying model classes to work.  Maybe there is an alternative serialization scheme where we don't need to modify the source classes.

File: elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/RedisAggregationDataStoreTestHarness.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import com.yahoo.elide.modelconfig.validator.DynamicConfigValidator;
+
+import redis.clients.jedis.JedisPooled;
+
+import java.util.Collections;
+import java.util.Map;
+import javax.persistence.EntityManagerFactory;
+import javax.sql.DataSource;
+
+public class RedisAggregationDataStoreTestHarness extends AggregationDataStoreTestHarness {
```
Comment (aklish) [inline elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/RedisAggregationDataStoreTestHarness.java:24]: I have mixed feelings about duplicating the IT tests here.   In one sense, it is good that we are testing many pathways through the cache.  On the other hand, this PR is making modifications to a lot of unrelated code. 
 Is there a way to test the RedisCache without pulling in all the IT tests?  Also, it would be great if RedisCache could "just work" on models without requiring changes to them.

**Comment by moizarafat** [comment]
@klish I did try using Jackson but it's not able to traverse the dynamic class structure it seems. 

`12:38:43.291 [qtp131723818-133] ERROR com.yahoo.elide.Elide.handleRuntimeException(Elide.java:638) - Error or exception uncaught by Elide
java.lang.IllegalStateException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["methods"]->com.yahoo.elide.core.type.EntityMethodType[4]->com.yahoo.elide.core.type.EntityMethodType["returnType"]->com.yahoo.elide.core.type.ClassType["superclass"]->com.yahoo.elide.core.type.ClassType["underlyingClass"])
	at com.yahoo.elide.datastores.aggregation.cache.RedisCache.put(RedisCache.java:65)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStoreTransaction.loadObjects(AggregationDataStoreTransaction.java:128)
	at com.yahoo.elide.datastores.multiplex.MultiplexTransaction.loadObjects(MultiplexTransaction.java:65)
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.lambda$loadObjects$2(InMemoryStoreTransaction.java:117)
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.fetchData(InMemoryStoreTransaction.java:262)
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.loadObjects(InMemoryStoreTransaction.java:123)
	at com.yahoo.elide.core.PersistentResource.loadRecords(PersistentResource.java:373)
	at com.yahoo.elide.jsonapi.parser.state.CollectionTerminalState.getResourceCollection(CollectionTerminalState.java:139)
	at com.yahoo.elide.jsonapi.parser.state.CollectionTerminalState.handleGet(CollectionTerminalState.java:75)
	at com.yahoo.elide.jsonapi.parser.state.StateContext.handleGet(StateContext.java:107)
	at com.yahoo.elide.jsonapi.parser.GetVisitor.visitQuery(GetVisitor.java:31)
	at com.yahoo.elide.jsonapi.parser.GetVisitor.visitQuery(GetVisitor.java:18)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:568)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.jsonapi.parser.BaseVisitor.visitStart(BaseVisitor.java:47)
	at com.yahoo.elide.jsonapi.parser.BaseVisitor.visitStart(BaseVisitor.java:33)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:117)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.yahoo.elide.Elide.visit(Elide.java:486)
	at com.yahoo.elide.Elide.lambda$get$1(Elide.java:265)
	at com.yahoo.elide.Elide.handleRequest(Elide.java:510)
	at com.yahoo.elide.Elide.get(Elide.java:258)
	at com.yahoo.elide.jsonapi.resources.JsonApiEndpoint.get(JsonApiEndpoint.java:103)
	at jdk.internal.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by moizarafat** [comment]
Unfortunately, Redis only supports byte[] or String for storing the values.

**Comment by moizarafat** [comment]
gson does not support `Iterable`, so that may need us to change the type of `data` in QueryResult to of type `Collections` but not sure if we will have some other impact cos of that.

**Comment by aklish** [comment]
What about kryo?  Does that require Java serializable?

**Comment by aklish** [comment]
I though kryo serializes to bytes

**Comment by moizarafat** [comment]
I am working on a Kyro based implementation on a separate branch. Will share once if it works end to end.

File: elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/RedisAggregationDataStoreTestHarness.java (hunk 2 above)
Comment (moizarafat) [reply elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/RedisAggregationDataStoreTestHarness.java:24]: I have separated the IT tests for Redis and Regular ones with Redis IT running a few of the test cases

**Comment by moizarafat** [comment]
As discussed we will start with Java Serialization in current release.

File: elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/NoCacheAggregationDataStoreIntegrationTest.java [hunk 3]
```diff
@@ -0,0 +1,2402 @@
+/*
+ * Copyright 2020, Yahoo Inc.
+ * Licensed under the Apache License, Version 2.0
+ * See LICENSE file in project root for terms.
+ */
+package com.yahoo.elide.datastores.aggregation.integration;
+
+import static com.yahoo.elide.test.graphql.GraphQLDSL.argument;
```
Comment (moizarafat) [inline elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/NoCacheAggregationDataStoreIntegrationTest.java:8]: Renamed AggregationDataStoreIntegrationTest as NoCacheAggregationDataStoreIntegrationTest where as an abstract class  AggregationDataStoreIntegrationTest with common functions.

File: elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java [hunk 4]
```diff
@@ -57,6 +57,8 @@
 @NoArgsConstructor
 @Builder
 public class Table implements Named {
```
Comment (aklish) [inline elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java:59]: Why do we need serialization for config models?  Is this for the ConfigDataStore tests?

Comment (moizarafat) [reply elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java:59]: Table config Model is an attribute of dynamic.TableType as shown here https://github.com/yahoo/elide/blob/9af2c6aac7f1f48dd9429421c547677b1d168bfb/elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/dynamic/TableType.java#L81. So in order to have TableType serializable had to make all it attribute classes serializable.

**Review by aklish — APPROVED** [review]
