### PR TITLE
Enum filter fix

### LINKED ISSUE #2407: Aggregation DataStore - cannot filter by enum type column
## Current Behavior
Not able to filter by enum type column

## Steps to Reproduce (for bugs)

1. Create 2 company instances
### company 1
```
curl --request POST 'http://localhost:8080/api/v1/company' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": {
        "type": "company",
        "id": "xyz",
        "attributes": {
            "type": "PRIVATE"
        }
    }
}'
```
### company 2
```
curl --request POST 'http://localhost:8080/api/v1/company' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": {
        "type": "company",
        "id": "abc",
        "attributes": {
            "type": "PUBLIC"
        }
    }
}'
```
2. Get company via JPA store using filter
it works perfectly.
```
curl --request GET 'http://localhost:8080/api/v1/company?filter[company]=type=in=PRIVATE' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json'
```

3. Get company via aggregation store
### with filter `ini`
An empty array is returned
```
curl --request GET 'http://localhost:8080/api/v1/report?filter[report]=type=ini=PRIVATE' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--header 'bypasscache: true'
```

### with filter `in`
An exception occurs
```
Caused by: org.h2.jdbc.JdbcSQLException: Hexadecimal string with odd number of characters: "0"; SQL statement:
SELECT DISTINCT `report`.`id` AS `companyId`,`report`.`type` AS `type` FROM `company` AS `report`  WHERE `report`.`type` IN (?)    LIMIT 500 OFFSET 0 [90003-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.util.StringUtils.convertHexToBytes(StringUtils.java:913)
	at org.h2.value.Value.convertTo(Value.java:1078)
	at org.h2.value.Value.convertTo(Value.java:617)
	at org.h2.value.Value.convertTo(Value.java:592)
	at org.h2.expression.Comparison.getValue(Comparison.java:271)
	at org.h2.expression.Expression.getBooleanValue(Expression.java:178)
	at org.h2.command.dml.Select.isConditionMet(Select.java:312)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1455)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:79)
	at org.h2.result.LazyResult.next(LazyResult.java:59)
	at org.h2.command.dml.Select.queryFlat(Select.java:527)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:633)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
	at org.h2.command.dml.Query.query(Query.java:371)
	at org.h2.command.dml.Query.query(Query.java:333)
	at org.h2.command.CommandContainer.query(CommandContainer.java:114)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.yahoo.elide.datastores.aggregation.queryengines.sql.NamedParamPreparedStatement.executeQuery(NamedParamPreparedStatement.java:47)
	at com.yahoo.elide.datastores.aggregation.queryengines.sql.SQLQueryEngine.lambda$runQuery$5(SQLQueryEngine.java:331)
```

## Your Environment

* Elide version used: 6.0.1
* Environment name and version (Java 1.8.0_152):JDK 15
* Operating System and version: MacOS
* Link to your project: [demo project](https://github.com/thaingo/elide-spring-boot-example/tree/verify-how-aggregation-store-supports-column-of-enum-type)

### PR DESCRIPTION
**Pull request by aklish**
Resolves #2407 

## Description
 - Reverts #2393 
 - Adds two new HJSON column types - ENUM_TEXT and ENUM_ORDINAL
 - Supports both text and numeric storage of HJSON defined enumerations (the enumeration values are stored as column 'values'.
 - Supports both text and numeric storage of Java defined enumerations (the storage type is extracted from the JPA `@Enumerated` annotation.

## How Has This Been Tested?
- New IT tests that both filter, sort and return the values of 4 classes of enumeration (HJSON and Java stored as ordinals or text).

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java [hunk 1]
```diff
@@ -98,11 +101,24 @@ protected Object coerceObjectToEntity(Map<String, Object> result, MutableInt cou
...
+
+            Type<?> fieldType = getType(entityClass, columnProjection);
+            Attribute attribute = projectionToAttribute(columnProjection, fieldType);
+
+            ValueType valueType = column.getValueType();
 
             if (entityInstance instanceof ParameterizedModel) {
+
+                //This is an ENUM_TEXT or ENUM_ORDINAL type.
+                if (! fieldType.isEnum()
```
Comment (moizarafat) [inline elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java:115]: separately messaged to clarify this

Comment (aklish) [reply elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java:115]: I'm not following.  Do you want me to add more comments on different lines?  What would you like to see?

Comment (moizarafat) [reply elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/EntityHydrator.java:115]: The comment says `This is an ENUM_TEXT or ENUM_ORDINAL type.` but the next line we are doing a negation of `fieldType.isEnum`. That confused me a bit.

**Review by moizarafat — APPROVED** [review]
