### PR TITLE
elide-datastore-aggregation: Fix build warnings

### LINKED ISSUE #1902: Fix elide-datastore-aggregation build warnings:
Fix the following build warnings for the aggregation data store:

```
[WARNING] /sd/workspace/src/github.com/yahoo/elide/elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Time.java:[27,1] Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
```

and 

```
[WARNING] /sd/workspace/src/github.com/yahoo/elide/elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java:[36,1] Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
```

### PR DESCRIPTION
**Pull request by moizarafat**
Resolves #1902

## Description
Fix Build warnings with Lombok.

## Motivation and Context
Resolve build warnings for Hacktogether

## How Has This Been Tested?
Existing Tests pass. Build warnings are gone.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Time.java [hunk 1]
```diff
@@ -24,7 +26,9 @@
 /**
  * Time date type for all analytic model time dimensions.
  */
-@Data
+@RequiredArgsConstructor
```
Comment (moizarafat) [inline elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Time.java:29]: Since we provide our own implementation of Hash, Equals and ToString using `@Data` annotation does not seem fit.

File: elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java [hunk 2]
```diff
@@ -33,7 +33,7 @@
  */
 @Include
 @VersionQuery(sql = "SELECT COUNT(*) from playerStats")
-@EqualsAndHashCode
+@EqualsAndHashCode(callSuper = false)
```
Comment (moizarafat) [inline elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java:36]: Using `true`, fails the test cases. So setting to `false` which is equivalent to default `skip`.

**Review by aklish — APPROVED** [review]
