### PR TITLE
Aggregation Store - Optimizer complex formula tests

### LINKED ISSUE #1983: AggregationStore : Join not detected in SQLReferenceTable.
The following definition of lastDate (and its dependent components), generates incorrect SQL.  Elide does not detect that lastDate requires a join.

```java
    @Temporal(grains = {
            @TimeGrainDefinition(grain = TimeGrain.DAY, expression = DATE_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.MONTH, expression = MONTH_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.QUARTER, expression = QUARTER_FORMAT)
    }, timeZone = "UTC")
    @DimensionFormula("{{$saleDate}}")
    private Day saleDate;

    @Temporal(grains = {
            @TimeGrainDefinition(grain = TimeGrain.DAY, expression = DATE_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.MONTH, expression = MONTH_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.QUARTER, expression = QUARTER_FORMAT)
    }, timeZone = "UTC")
    @DimensionFormula("{{playerStats.recordedDate}}")
    private Day sessionDate;

    @Temporal(grains = {
            @TimeGrainDefinition(grain = TimeGrain.DAY, expression = DATE_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.MONTH, expression = MONTH_FORMAT),
            @TimeGrainDefinition(grain = TimeGrain.QUARTER, expression = QUARTER_FORMAT)
    }, timeZone = "UTC")
    @DimensionFormula("CASE WHEN {{sessionDate}} > {{saleDate}} THEN {{sessionDate}} ELSE {{saleDate}} END")
    private Day lastDate;
```

### PR DESCRIPTION
**Pull request by aklish**
Final set of tests for query plan optimizer.  Also resolve #1983.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java [hunk 1]
```diff
@@ -110,9 +111,16 @@ public TimeGrain getGrain() {
...
-            //TODO - the expression needs to be rewritten to leverage the inner column physical projections.
+            PhysicalRefColumnContext context = PhysicalRefColumnContext.physicalRefContextBuilder()
+                    .queryable(source)
+                    .alias("")
+                    .metaDataStore(store)
+                    .column(this)
+                    .tableArguments(source.getArguments())
+                    .build();
+            outerProjection = withExpression(context.resolve(getExpression()), inProjection);
+
```
Comment (rishi-aga) [inline elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLTimeDimensionProjection.java:123]: may be use `toPhysicalReferences` method in SQLColumnProjection

**Review by rishi-aga — APPROVED** [review]
